#ifndef _BOARD_CONFIG_H_
#define _BOARD_CONFIG_H_

#include <driver/gpio.h>

#define AUDIO_INPUT_SAMPLE_RATE  16000
#define AUDIO_OUTPUT_SAMPLE_RATE 16000

#define AUDIO_INPUT_CHANNELS     3
#define AUDIO_INPUT_REFERENCE    true

#define AUDIO_OUTPUT_I2S_GPIO_MCLK GPIO_NUM_42
#define AUDIO_OUTPUT_I2S_GPIO_BCLK GPIO_NUM_40
#define AUDIO_OUTPUT_I2S_GPIO_WS   GPIO_NUM_41
#define AUDIO_OUTPUT_I2S_GPIO_DOUT GPIO_NUM_39

#define AUDIO_INPUT_I2S_GPIO_MCLK  GPIO_NUM_20
#define AUDIO_INPUT_I2S_GPIO_BCLK  GPIO_NUM_10
#define AUDIO_INPUT_I2S_GPIO_WS    GPIO_NUM_9
#define AUDIO_INPUT_I2S_GPIO_DIN   GPIO_NUM_11

#define AUDIO_CODEC_PA_PIN       GPIO_NUM_38
#define AUDIO_CODEC_I2C_PORT     I2C_NUM_0
#define AUDIO_CODEC_I2C_SDA_PIN  GPIO_NUM_1
#define AUDIO_CODEC_I2C_SCL_PIN  GPIO_NUM_2
#define AUDIO_CODEC_ES8311_ADDR  ES8311_CODEC_DEFAULT_ADDR
#define AUDIO_CODEC_ES7210_ADDR  ES7210_CODEC_DEFAULT_ADDR

#define BOOT_BUTTON_GPIO GPIO_NUM_0

#define BUILTIN_LED_GPIO GPIO_NUM_19
#define BUILTIN_LED_NUM  12

#endif // _BOARD_CONFIG_H_
